---
title: "Exploratory Data Analysis Brush Up"
author: "Orumwese Esosa Cyriaque"
date: "8/2/2021"
output:
  html_document: default
  pdf_document: default
---
```{r}
library(tidyverse)
```

# V A R I A T I O N

```{r,echo=TRUE}
ggplot(data = diamonds) +
        geom_bar(mapping = aes(x=cut))
```

```{r,echo=TRUE}
ggplot(diamonds) + 
        geom_histogram(mapping = aes(x=carat), binwidth = 0.5)

count(diamonds, cut_width(carat,0.5))
```

```{r,echo=TRUE}
smaller <- diamonds %>% 
        filter(carat<1)

ggplot(data = smaller, mapping = aes(x = carat)) + 
        geom_histogram(binwidth = 0.01)

ggplot(data = smaller, mapping = aes(x = carat, color = cut)) +
        geom_freqpoly(binwidth = 0.01)
```

```{r,old faithful,echo=TRUE}
ggplot(data=faithful, mapping=aes(x=eruptions)) + 
        geom_histogram(binwidth=0.25)
# clustered into two groups. Short eruptions(~2mins) and long eruptions(>5mins)
```

```{r,outliers,echo=TRUE}
ggplot(diamonds) + 
        geom_histogram(mapping = aes(x=y), binwidth = 0.5)

# Zooming in for a closer look
ggplot(diamonds) + 
        geom_histogram(mapping = aes(x=y), binwidth = 0.5) + 
        coord_cartesian(ylim = c(0,50))
# It is noticed that there are 3 outliers: 0, ~30, and ~60.
```
```{r,echo=TRUE}
unusual <- diamonds %>%
        filter(y<3|y>20) %>%
        arrange(y)
unusual
```

```{r,missing values,echo=TRUE}
# Removes outliers by making them NA values
diamonds2 <- diamonds %>%
        mutate(y = ifelse(y<3|y>20,NA,y))

ggplot(data=diamonds2, mapping=aes(x=x,y=y)) +
        geom_point()

ggplot(data=diamonds, mapping=aes(x=x,y=y)) +
        geom_point()
```

# C O V A R I A T I O N

```{r,echo=TRUE}
# Displaying the uselessness of the def appearance of geom_freqpoly()
# It makes it hard to see the differences in shape to the data compared being different

ggplot(data=diamonds, mapping=aes(x=price)) +
        geom_freqpoly(mapping=aes(color=cut), binwidth=500)

# It's hard to see the difference in distribution because the overall counts differ so much
ggplot(diamonds) + geom_bar(mapping=aes(x=cut))
```

```{r,echo=TRUE}
# This issue can be solved via standardization and this is achieved by replacing count (on y axis) with with density.
# Density is count standardized so that the area under each frequency polygon is 1.

ggplot(diamonds, aes(x=price, y=..density..)) +
        geom_freqpoly(aes(color=cut), binwidth=500)

# Frequency Plots are a little hard to interprete
```

```{r,boxplots,echo=TRUE}
ggplot(diamonds, aes(x=cut, y=price)) +
        geom_boxplot()
```
```{r,echo=TRUE}
ggplot(mpg, aes(x=class, y=hwy)) +
        geom_boxplot()
```
```{r,echo=TRUE}
# Reordering class based on median value of hwy

ggplot(mpg) + 
        geom_boxplot(aes(x=reorder(class, hwy, FUN=median), y=hwy))

# flipping plot
ggplot(mpg) + 
        geom_boxplot(aes(x=reorder(class, hwy, FUN=median), y=hwy)) +
        coord_flip()

```

## Two Categorical Variables
```{r,echo=TRUE}
# Visualizing the covariation between two categorical variables
# Use geom_count()

ggplot(diamonds) +
        geom_count(aes(x=cut, y=color))
```

```{r,echo=TRUE}
# Another approach is to compute the count with dplyr and then visualize with geom_tile()

diamonds %>%
        count(color,cut)

diamonds %>%
        count(color,cut) %>%
        ggplot(aes(x=color, y=cut)) +
        geom_tile(aes(fill=n))

```

## Two Continuous Variables
```{r,echo=TRUE}
# Visualization using a scatterplot.

ggplot(diamonds) +
        geom_point(aes(y=price, x=carat))

# Enhancing readability by adding transparency
ggplot(diamonds) +
        geom_point(aes(y=price, x=carat), alpha = 0.01)


```

```{r,echo=TRUE}
# Don't get this sha
ggplot(smaller, aes(x=carat, y=price)) +
        geom_boxplot(aes(group=cut_width(carat, 0.1)))

```



























